steps:
  # Dockerイメージのビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/x-fab-php-app', '.']
  
  # イメージをContainer Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/x-fab-php-app']
  
  # Cloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'x-fab-php-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/x-fab-php-app'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '$_CLOUD_SQL_CONNECTION_NAME'
      - '--set-env-vars'
      - 'DB_HOST=/cloudsql/$_CLOUD_SQL_CONNECTION_NAME,DB_NAME=x_fab_db,DB_USER=$_DB_USER,DB_PASS=$_DB_PASS,ENV=production'

substitutions:
  _CLOUD_SQL_CONNECTION_NAME: YOUR_PROJECT_ID:asia-northeast1:x-fab-db
  _DB_USER: x_fab_user
  _DB_PASS: YOUR_SECURE_PASSWORD

images:
  - 'gcr.io/$PROJECT_ID/x-fab-php-app'